### ISSUE TITLE
Use directly in memory, instead of via files, possible?

### ISSUE THREAD

**Issue by carlthome** [rabitt/pysox#6] opened 2016-06-27 16:00 UTC
Would it be possible to input audio as ndarray:s into pysox directly as well as files from disk? Why I'm asking is because I'm using librosa for onset detection, and thus already have the audio loaded, but would still like to apply some audio effects and stuff afterwards.

Like maybe the constructors could do a type check, and build() could return the destination audio or something?

``` Python
y = librosa.load(path)[0]
tfm = sox.Transformer(y)
# Do stuff...
y = tfm.build()
```

I realize this adds extra complexity to pysox (like having librosa as a dependency or similar) which is intended to be a clean wrapper around SoX, so I get if it's deemed out of scope. Just asking!

**Comment by rabitt** [comment] 2016-08-06 16:06
I thought about this, and I decided it's out of scope for this library. I'd suggest simply writing the audio back to disk and then using pysox on the file. I realize this isn't ideal, but I think to do this in pysox without saving the audio first requires a lot of command line witchery ;).

That said, if you find a clean way to do it, I'm happy to look at the PR.

**Comment by carlthome** [comment] 2016-08-16 18:50
Ok, but it's just a matter of piping. sox supports piping stdin/stdout with the `-` flag, like:

```Python
from subprocess import Popen, PIPE

import librosa as lr
import numpy as np

# Load an example audio file into memory with librosa.
y, sr = lr.load(lr.util.example_audio_file())

# Do stuff with the audio samples here...

# Then apply reverb with sox without having to writing an intermediate file.
pipe = Popen(['sox', '-t', 'raw', '-', '-t', 'raw', '-', 'reverb'],
             stdout=PIPE,
             stderr=PIPE)
y = np.frombuffer(p.communicate(mix.tobytes())[0])
```

**Comment by justinsalamon** [comment] 2016-10-05 20:37
Not that this solves the issue of taking an i/o hit, but in the meanwhile a safe way to concatenate operations is to use ```tempfile```:

```python
with tempfile.NamedTemporaryFile(suffix='.wav') as tmp:

    tfm = sox.Transformer()
    tfm.trim(0, 5)
    tfm.build(infile, tmp.name)

    cbn = sox.Combiner()
    cbn.build([tmp.name, tmp.name], outfile, 'concatenate')
```
The downside is that since sox requires a filename, you need to use a ```NamedTemporaryFile``` and that means the system will think the file already exists when you call ```build()```, which means you'll always get an overwrite warning (which perhaps could be disabled by the addition of an optional flag @rabitt ?)

Right now the workaround is by changing the logger level:

```python
logger = logging.getLogger()
logger.setLevel('CRITICAL')
    
with tempfile.NamedTemporaryFile(suffix='.wav') as tmp:

    tfm = sox.Transformer()
    tfm.trim(0, 5)
    tfm.build(infile, tmp.name)

    cbn = sox.Combiner()
    cbn.build([tmp.name, tmp.name], outfile, 'concatenate')

logger.setLevel('WARNING')
```
Or if you just want to suppress all logging you can do ```logger.disabled = True```

**Comment by carlthome** [comment] 2016-10-06 15:16
@justinsalamon, @rabitt, I've published a lightweight SoX effects wrapper (reverb, phaser, delay, etc.) that pipes NumPy ndarrays over stdin/stdout instead of creating extra I/O load with tempfiles. Maybe you can use bits of it in pysox: https://github.com/carlthome/python-audio-effects

**Comment by rabitt** [comment] 2016-10-07 17:31
@justinsalamon can you open a separate issue about optionally disabling the overwrite warning?

**Comment by rabitt** [comment] 2016-10-07 17:32
@carlthome Looks awesome! I plan to include this feature when I bump to v1.3

**Comment by justinsalamon** [comment] 2016-10-11 16:36
> @justinsalamon can you open a separate issue about optionally disabling the overwrite warning?

#25

**Comment by smolendawid** [comment] 2018-01-17 12:55
I must admit that it would be very useful. I need this transformations on the fly, holding everything in RAM, so saving to a disk and then again loading to python is inefficient.

**Comment by hadware** [comment] 2018-01-27 23:27
I'll try porting @carlthome 's work to pysox, It'd be nice if you guys could give me some pointers on how you'd wish it to be implemented. I'd personally see it as another method on the transformer and combine class to *output* a numpy ndarray, such as `build_ndarray`.

To input ndarray soundfiles, i guess this could be just some slight modifications on the args of the `build` method.

**Comment by carlthome** [comment] 2018-02-04 14:41
Sound great! I'd love to get rid of [my package](https://github.com/carlthome/python-audio-effects) entirely and have pysox be the only SoX Python wrapper if possible.

Consolidate:
![image](https://user-images.githubusercontent.com/1595907/35778675-d7bb7cae-09c1-11e8-9624-5fc4cc9f0e95.png)

**Comment by lostanlen** [comment] 2018-08-02 15:57
@carlthome I don't think that solving this issue would require having all of librosa as a dependency. Since it's purely a matter of I/O, `pysoundfile` is sufficient for the most common lossless formats: WAV / FLAC / OGG

**Comment by rabitt** [comment] 2018-08-10 16:07
@hadware -

> I'll try porting @carlthome 's work to pysox, It'd be nice if you guys could give me some pointers on how you'd wish it to be implemented. I'd personally see it as another method on the transformer and combine class to output a numpy ndarray, such as build_ndarray.

I agree that what makes the most sense is to have a separate function `build_array` that mirrors `build` but inputs and outputs an ndarray. I prefer this to overloading the current `build` function. 

> To input ndarray soundfiles, i guess this could be just some slight modifications on the args of the build method.

Yes, as far as I can tell it's doable by changing the input and output filename to the `-` character and piping the audio data to stdin. Some relevant info in the [SoX documentation](http://sox.sourceforge.net/sox.html) in the section on "Special Filenames".

In terms of capturing the audio data from stdout, I think everything is already in place, but if you run into issues, [this is where the problem is likely to be](https://github.com/rabitt/pysox/blob/master/sox/core.py#L45).

Let me know if you need any help!

**Comment by pseeth** [comment] 2020-05-15 22:29
I'm going to give addressing this issue a shot, mostly by trying to port @carlthome's pysndfx fix into this library. Do people have the bandwidth for a PR for this soon (hopefully)? Looking over the comments here, I believe such a change would require adding `numpy` as a dependency.

**Comment by rabitt** [comment] 2020-05-21 13:12
This is done in #102 , thanks @pseeth !
I've opened #106 to discuss how the API should look moving foward before pushing to a full release.

**Closed by rabitt** 2020-05-21 13:12 UTC
Labels: enhancement

**Comment by danihodovic** [comment] 2022-09-27 14:00
Is it possible to use the `file_info` API with in memory files?
