### ISSUE TITLE
Converting wav to vox

### ISSUE THREAD

**Issue by muzaluisa** [rabitt/pysox#90] opened 2019-03-06 08:51 UTC
Hey,

I was wondering if we can run the same command using pysox but to output file to python var instead of writing to a new file?)

`sox file.wav -t vox -r 8000 file.vox`

**Comment by lostanlen** [comment] 2019-03-06 15:00
@muzaluisa i'm not sure what your use case is here. If i understand it correctly, your command converts a headerless Vox file with a WAV extension, assigns it a sample rate of 8 kHz in the header, and eventually writes the result to a `.vox` extension. Is that right?
And then what you want is to load the result onto Python?

**Comment by lostanlen** [comment] 2019-07-04 13:59
AFAICT this is likely a quasi-duplicate of #6. We haven't had more details from OP in four months to it's difficult to act upon this specific issue. I'm going to close this one and redirect conversation to #6

**Closed by lostanlen** 2019-07-04 13:59 UTC
